# Generated by Django 5.0.14 on 2025-05-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of amenities, e.g. Projector, Whiteboard",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
