# Generated by Django 5.0.14 on 2025-05-22 21:35

import django.db.models.deletion
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=reservations.models._default_date)),
                (
                    "hour",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (8, "08:00"),
                            (9, "09:00"),
                            (10, "10:00"),
                            (11, "11:00"),
                            (12, "12:00"),
                            (13, "13:00"),
                            (14, "14:00"),
                            (15, "15:00"),
                            (16, "16:00"),
                            (17, "17:00"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "hour"),
                "unique_together": {("room", "date", "hour")},
            },
        ),
    ]
